/**
 * Time Utility Library
 * Centralized logic specifically for handling "HH:mm" time strings generated by standard HTML time inputs.
 * Ensures strict calculation, comparison, and formatting for Booking/Scheduling modules.
 */

/**
 * Converts a 24-hour "HH:mm" string into a readable 12-hour AM/PM format.
 * Ex: "14:30" -> "2:30 PM"
 * 
 * @param {string} time24 
 * @returns {string}
 */
export const format12Hour = (time24) => {
  if (!time24) return '';
  const [hoursStr, minutesStr] = time24.split(':');
  let hours = parseInt(hoursStr, 10);
  const minutes = minutesStr;
  
  const ampm = hours >= 12 ? 'PM' : 'AM';
  hours = hours % 12;
  hours = hours ? hours : 12; // the hour '0' should be '12'
  
  return `${hours}:${minutes} ${ampm}`;
};

/**
 * Converts a "HH:mm" string into total elapsed minutes from 00:00 midnight.
 * Crucial for mathematical time comparisons.
 * 
 * @param {string} timeStr 
 * @returns {number}
 */
const timeToMinutes = (timeStr) => {
  if (!timeStr) return 0;
  const [h, m] = timeStr.split(':').map(Number);
  return (h * 60) + m;
};

/**
 * Validates that the chronological order of a booking block is mathematically sound.
 * Fails if start time is equal to or after end time.
 * 
 * @param {string} startTime - "HH:mm"
 * @param {string} endTime - "HH:mm"
 * @returns {boolean}
 */
export const isValidTimeOrder = (startTime, endTime) => {
  if (!startTime || !endTime) return false;
  return timeToMinutes(startTime) < timeToMinutes(endTime);
};

/**
 * Calculates the exact duration (in minutes) between two time boundaries.
 * 
 * @param {string} startTime - "HH:mm"
 * @param {string} endTime - "HH:mm"
 * @returns {number} - Duration in minutes
 */
export const calculateDurationMins = (startTime, endTime) => {
  if (!startTime || !endTime) return 0;
  const startMins = timeToMinutes(startTime);
  const endMins = timeToMinutes(endTime);
  const diff = endMins - startMins;
  return diff > 0 ? diff : 0; // Prevent negative durations
};

/**
 * Helper to display duration cleanly (e.g. "1h 30m" instead of "90 mins")
 * 
 * @param {number} totalMinutes 
 * @returns {string}
 */
export const formatDurationString = (totalMinutes) => {
  if (totalMinutes <= 0) return '0m';
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  
  let formatted = '';
  if (hours > 0) formatted += `${hours}h `;
  if (minutes > 0) formatted += `${minutes}m`;
  return formatted.trim();
};

/**
 * Detects if a requested time block collides with an existing booked block.
 * Extremely important for the Facilities conflict-resolution engine.
 * 
 * @param {string} reqStart - "HH:mm"
 * @param {string} reqEnd - "HH:mm"
 * @param {string} bookedStart - "HH:mm"
 * @param {string} bookedEnd - "HH:mm"
 * @returns {boolean} - True if intersection exists
 */
export const isTimeOverlapping = (reqStart, reqEnd, bookedStart, bookedEnd) => {
  const rStart = timeToMinutes(reqStart);
  const rEnd = timeToMinutes(reqEnd);
  const bStart = timeToMinutes(bookedStart);
  const bEnd = timeToMinutes(bookedEnd);

  // Math overlap logic: A intersects B if A.start < B.end AND A.end > B.start
  return rStart < bEnd && rEnd > bStart;
};

const timeUtils = {
  format12Hour,
  isValidTimeOrder,
  calculateDurationMins,
  formatDurationString,
  isTimeOverlapping,
};

export default timeUtils;
